### PR TITLE
[1.18.2] Fix for shader performance issue with Immersive Engineering installed

### LINKED ISSUE #71: Performance regression using Oculus pre-release version along with Immersive Engineering
Immersive Engineering seems to be causing performance issues on the latest Oculus pre-release version for 1.16.5

Reproduction Steps (tested using Complementary Shaders)

1. Load Oculus and Rubidium and any other mods EXCEPT Immersive Engineering
Join a Superflat world
Enable shaders and observe a stable and smooth framerate

2. Load Oculus, Rubidium, and Immersive Engineering
Join a Superflat world
Enable shaders and observe a huge performance decrease with just Immersive Engineering in the modlist

For reference, here is my current modlist that runs Oculus shaders perfectly until Immersive Engineering: https://pastebin.com/PqqbYCAn

### Screenshots

_No response_

### Relevant log output

_No response_

### Minecraft Version

Minecraft 1.16.5

### Iris Version

oculus-1.2.3-pre

### Sodium Version

rubidium-0.2.6.jar

### Operating System

Windows 10

### What is your GPU?

NVidia Geforce 1060

### Java Version

Java 8

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by r8420**
Reverts some DepthTexture code to a previous version because the current code heavily impacts performance with the Immersive Engineering mod installed. Fixes #71 (for 1.18.2)

### CODE REVIEW

**Comment by SmokePuddingEveryday** [comment]
Awesome! Do you know if a fix for the 1.16.5 version would be a similar process?

**Comment by DejaVuMan** [comment]
Would love to test this out on my own - how do I compile this locally? looks like the import statements for me.jellysquid.mods.X can't find the jar file to get it from.

**Comment by r8420** [comment]
> Would love to test this out on my own - how do I compile this locally? looks like the import statements for me.jellysquid.mods.X can't find the jar file to get it from.

**For 1.18:**
Create a libs folder in the root of the project. Then you need to put 3 files in that folder:
-apache-ant-1.8.2.jar [(download here)](http://www.java2s.com/Code/JarDownload/apache-ant/apache-ant-1.8.2.jar.zip)
-flywheel-forge-1.18-0.6.1.jar [(download here)](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3687357)
-rubidium-0.5.1.jar [(download here)](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3670969)
That's how I got it to work.
For 1.16 I was unable to get it compiled locally.

**Comment by IMS212** [comment]
Reversing this code is not a valid fix. This change was made to heavily improve compatibility, by not ignoring Vanilla's depth changes.

**Comment by r8420** [comment]
I forgot this pull request was still open. This was only meant as a temporary fix. For more info check the PR for 1.16. This is already fixed in the newest version I believe.

**Pull request closed without merging**
