### PR TITLE
Update gradle-wrapper.properties

### PR DESCRIPTION
**Pull request by EchoEllet**

### CODE REVIEW

**Comment by dima-dencep** [comment]
????

**Comment by EchoEllet** [comment]
> ???? 

This update Gradle build system version, it doesn't have any breaking changes

**Comment by dima-dencep** [comment]
This does NOT update the version of the Gradle build system, because you just changed the number in the gradle-wrapper.prop file

**Comment by EchoEllet** [comment]
> This does NOT update the version of the Gradle build system, because you just changed the number in the gradle-wrapper.prop file

It's not a major version, only improvements and features, doesn't have any breaking changes, the version number is in that file and that's how you update it in Gradle, if we're upgrading to 9 then we should do many more changes, I get it, it was very simple change, I was using your mod and on my way I send this PR, I don't planning on doing more because I'm not familiar with Minecraft apis, only Java

**Comment by EchoEllet** [comment]
> This does NOT update the version of the Gradle build system, because you just changed the number in the gradle-wrapper.prop file

There is even an action for that:
https://github.com/gradle-update/update-gradle-wrapper-action

All what it do is change the number

**Comment by dima-dencep** [comment]
To properly update gradle, you needed to run the `wrapper --gradle-version latest` task, which would update more than just the version in gradle-wrapper.properties

**Comment by dima-dencep** [comment]
We don't plan to make any changes to the build system at this time (only if we switch to the one iris is currently using)

**Pull request closed without merging**
