### PR TITLE
[1.16.5] Fix for shader performance issue with Immersive Engineering installed

### LINKED ISSUE #71: Performance regression using Oculus pre-release version along with Immersive Engineering
Immersive Engineering seems to be causing performance issues on the latest Oculus pre-release version for 1.16.5

Reproduction Steps (tested using Complementary Shaders)

1. Load Oculus and Rubidium and any other mods EXCEPT Immersive Engineering
Join a Superflat world
Enable shaders and observe a stable and smooth framerate

2. Load Oculus, Rubidium, and Immersive Engineering
Join a Superflat world
Enable shaders and observe a huge performance decrease with just Immersive Engineering in the modlist

For reference, here is my current modlist that runs Oculus shaders perfectly until Immersive Engineering: https://pastebin.com/PqqbYCAn

### Screenshots

_No response_

### Relevant log output

_No response_

### Minecraft Version

Minecraft 1.16.5

### Iris Version

oculus-1.2.3-pre

### Sodium Version

rubidium-0.2.6.jar

### Operating System

Windows 10

### What is your GPU?

NVidia Geforce 1060

### Java Version

Java 8

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by r8420**
Just like pull request #79 it reverts some DepthTexture code to a previous version because the current code heavily impacts performance with the Immersive Engineering mod installed. 

**I was not able to test this one locally so it should be tested.**

Hopefully fixes https://github.com/Asek3/Oculus/issues/71 (for 1.16.5)

### CODE REVIEW

**Comment by kylanpl** [comment]
If someone can give me a quick rundown on how to build this I can test

**Comment by segg21** [comment]
> If someone can give me a quick rundown on how to build this I can test

https://github.com/r8420/Oculus/tree/temp-fix-ImmersiveEngineering
https://www.tutorialspoint.com/gradle/gradle_build_a_java_project.htm

**Comment by xieve** [comment]
Because the gradle config uses local file dependency artifacts whithout a documented source, I'm not able to build. It might be worth considering switching to online sources such as mvnrepository.com for Apache ANT and jitpack.io or similar for Rubidium and Flywheel, that would greatly enhance the reproducability of builds and lower the hurdle to contribute.

Edit: That being said, I'd also be willing to test drive a built jar.

**Comment by SmokePuddingEveryday** [comment]
> https://github.com/r8420/Oculus/tree/temp-fix-ImmersiveEngineering
> https://www.tutorialspoint.com/gradle/gradle_build_a_java_project.htm

Getting this error when attempting to compile it. Let me know if I'm doing something wrong or how to provide a log if needed.

[Error](https://i.imgur.com/NTtEyoc.png)

**Comment by kylanpl** [comment]
> > If someone can give me a quick rundown on how to build this I can test
> 
> https://github.com/r8420/Oculus/tree/temp-fix-ImmersiveEngineering https://www.tutorialspoint.com/gradle/gradle_build_a_java_project.htm

Sorry, I wasn't clear enough. Even after downloading all the lib jars and adding them to the libs folder, I still can't get Oculus 1.16.5 to build locally with or without this fix so I can't test it. The person who made this PR was also unable to test it:

> > Would love to test this out on my own - how do I compile this locally? looks like the import statements for me.jellysquid.mods.X can't find the jar file to get it from.
> 
> **For 1.18:** Create a libs folder in the root of the project. Then you need to put 3 files in that folder: -apache-ant-1.8.2.jar [(download here)](http://www.java2s.com/Code/JarDownload/apache-ant/apache-ant-1.8.2.jar.zip) -flywheel-forge-1.18-0.6.1.jar [(download here)](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3687357) -rubidium-0.5.1.jar [(download here)](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3670969) That's how I got it to work. **For 1.16 I was unable to get it compiled locally.**



[Here](https://www.toptal.com/developers/hastebin/juqememeke.typescript) is the full log of my build attempt:

**Comment by coderbot16** [comment]
This is not the correct way to fix the problem, since it will issues in other parts of the code. In particular, since the depth texture is will not be copied to the main Minecraft framebuffer in any way with these changes, some mod compatibility code will break.

This is a more proper fix in upstream Iris that will be released in Iris 1.2.5: https://github.com/IrisShaders/Iris/compare/ffb27420814f8dc0c71860fcb0d82d091eea0806...c8d2f6a40b2603a784c63772f47e18a3fef00e42

**Comment by coderbot16** [comment]
You did correctly identify that this was related to the depth buffer copy code, however... what's going on here is that Iris is trying to ensure that it uses Minecraft's depth buffer directly for better mod compat, but unfortunately this caused a bunch of other issues, including this slowdown (caused by a format conversion in a copy call), and apparently a bunch of issues with white dots appearing on the screen. All of these things are planned to be fixed in upstream Iris 1.2.5, with the end goal of having better mod compatibility overall.

**Comment by r8420** [comment]
> You did correctly identify that this was related to the depth buffer copy code, however... what's going on here is that Iris is trying to ensure that it uses Minecraft's depth buffer directly for better mod compat, but unfortunately this caused a bunch of other issues, including this slowdown (caused by a format conversion in a copy call), and apparently a bunch of issues with white dots appearing on the screen. All of these things are planned to be fixed in upstream Iris 1.2.5, with the end goal of having better mod compatibility overall.

Thanks for clarifying. I already knew this wasn't the correct way to fix this, I just reverted some changes to the depth texture code to temporary fix this issue. It's good to know that this will be fixed in an upcoming version of Iris.

**Comment by KitsuneDev** [comment]
Did anyone manage to build this fork? Currently running into this issue, and I'm unable to find the artefacts needed for a local build.

**Comment by SmokePuddingEveryday** [comment]
> Did anyone manage to build this fork? Currently running into this issue, and I'm unable to find the artefacts needed for a local build.

Correct me if I'm wrong, but I thought this was fixed in the newer versions of Oculus for 1.16.5?

**Pull request closed without merging**
